# Generated by Django 4.1.6 on 2023-02-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "The Username provided is already taken."
                        },
                        max_length=25,
                        unique=True,
                    ),
                ),
                ("password", models.TextField()),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("gender", models.CharField(max_length=30)),
                ("dob", models.DateField(blank=True)),
                ("preferred_name", models.CharField(blank=True, max_length=25)),
                ("bot_name", models.CharField(blank=True, max_length=25)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address_line1", models.CharField(max_length=128)),
                ("address_line2", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(max_length=64)),
                ("state", models.CharField(max_length=64)),
                ("country", models.CharField(max_length=64)),
                ("zip_code", models.CharField(max_length=6)),
                ("phone_number", models.CharField(blank=True, max_length=12)),
                ("ethnicity", models.CharField(blank=True, max_length=30)),
                ("issue_diagnosed", models.BooleanField()),
                ("issue_type", models.TextField(blank=True)),
                ("issue_duration", models.CharField(blank=True, max_length=30)),
                ("caregiver", models.BooleanField()),
            ],
            options={"db_table": "user",},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="user_usernam_b79065_idx"),
        ),
    ]
